### Section 1: Creating Arrays

##### Q1. Create a 1D NumPy array from the list [10, 20, 30, 40] and print it.

In [1]:
import numpy as np
arr = np.array([10, 20, 30, 40])
print(arr)

[10 20 30 40]


##### Q2. What is the output of np.array([[1, 2], [3, 4]])?

In [2]:
arr = np.array([[1, 2], [3, 4]])
print(arr)

[[1 2]
 [3 4]]


##### Q3. Write a line of code to create a 3x2 array filled with the number 9

In [4]:
arr = np.full((3 ,2) , 9)
print(arr)

[[9 9]
 [9 9]
 [9 9]]


##### Q4. Use NumPy to create a 2x3 array filled with 1s

In [10]:
arr = np.ones((2 , 3)).astype(int)
print(arr)

[[1 1 1]
 [1 1 1]]


##### Q5. Create a NumPy array using np.arange() that starts at 5, ends before 20, and has a step of 3

In [11]:
arr = np.arange(5 , 20 , 3)
print(arr)

[ 5  8 11 14 17]


##### Q6. Write the code to create a 4x4 identity matrix.

In [13]:
arr = np.eye(4,4).astype(int)
print(arr)

[[1 0 0 0]
 [0 1 0 0]
 [0 0 1 0]
 [0 0 0 1]]


## Section 2: Array Attributes

##### Q7. Given arr = np.array([1, 2, 3, 4]), what is arr.shape and arr.ndim?

In [22]:
arr = np.array([1, 2, 3, 4])
print(arr)
print(f"shape : {arr.shape} , dimension : {arr.ndim}")

[1 2 3 4]
shape : (4,) , dimension : 1


##### Q8. Convert the array arr = np.array([10, 20]) to float type using NumPy

In [23]:
arr = np.array([10, 20]).astype(float)
print(arr)

[10. 20.]


## Section 3: Indexing & Slicing

##### Q9. Given mat = np.array([[10, 20, 30], [40, 50, 60]]), what is mat[1, 2]?

In [24]:
mat = np.array([[10, 20, 30], [40, 50, 60]])
# what is mat[1, 2] => 1 row , 2 column
print(mat[1 , 2])

60


##### Q10. Extract all rows and the second column using slicing.

In [29]:
arr = np.array([[10, 20, 30], [40, 50, 60]])
print(arr[:,1])

[20 50]


##### Q11. From arr = np.array([5, 10, 15, 20, 25]), extract elements greater than 15 using boolean masking.

In [32]:
arr = np.array([5, 10, 15, 20, 25])
print(arr > 15)
print(arr[arr > 15])

[False False False  True  True]
[20 25]


##### Q12. Use fancy indexing to extract the 1st, 3rd, and 5th elements.

In [34]:
arr = np.array([5, 10, 15, 20, 25])
print(arr[[0,2,4]])

[ 5 15 25]


## Section 4: Aggregate Functions

##### Q13. Calculate the mean, median, and sum of arr = np.array([1, 3, 5, 7])

In [42]:
arr = np.array([1, 3, 5, 7])
print(f"\n Mean : {np.mean(arr)}  \n Median : {np.median(arr)} \n Sum : {np.sum(arr)} ")


 Mean : 4.0  
 Median : 4.0 
 Sum : 16 


##### Q14. What does np.argmax(np.array([1, 3, 7, 2])) return?

In [44]:
arr = np.array([1, 3, 5, 7])
print(np.argmax(arr)) # return index of maximum element

3


## Section 5: Element-wise Operations

##### Q15. Given a = np.array([1, 2, 3]) and b = np.array([4, 5, 6]), what is the result of a * b?

In [35]:
a = np.array([1, 2, 3])
b = np.array([4, 5, 6])
print(a*b)

[ 4 10 18]


##### Q16. What happens if you do a + 10?

In [36]:
a = np.array([1, 2, 3])
print(a + 10)

[11 12 13]


## Section 6: Reshaping & Flattening

##### Q17. Reshape np.array([[1, 2, 3], [4, 5, 6]]) into a 3x2 array

In [45]:
arr = np.array([[1, 2, 3], [4, 5, 6]]).reshape(3 ,2)
print(arr)


[[1 2]
 [3 4]
 [5 6]]


##### Q18. Flatten np.array([[1, 2], [3, 4]]) using flatten() and ravel(). How are they different?

In [49]:
arr = np.array([[1, 2], [3, 4]])
 #flatten   changes effect original
 # ravel   changes do not effect original
print(arr.flatten() ,arr.ravel())

[1 2 3 4] [1 2 3 4]


## Section 7: Random Numbers

##### Q19. Generate 5 random integers between 10 and 20 using NumPy.

In [51]:
arr = np.random.randint(10 , 21 , size = 5)
print(arr)

[20 14 10 13 10]


##### Q20. Generate a 1D array of 4 random floats between 0 and 1.

In [59]:
arr = np.random.rand(4)
print(arr)

[0.49928599 0.04979709 0.65471204 0.3830283 ]


## Section 8: Stacking & Splitting

##### Q21. Stack a = [1, 2] and b = [3, 4] vertically using np.vstack.

In [63]:
a = [1, 2] 
b = [3, 4] 
print(np.vstack((a , b))) # axis = 0


[[1 2]
 [3 4]]


##### Horizontally split this array: a = np.array([[1, 2, 3, 4], [5, 6, 7, 8]]) into two equal parts.

In [70]:
 a = np.array([[1, 2, 3, 4], [5, 6, 7, 8]])
print(np.split(a , 2 , axis = 1)) 

[array([[1, 2],
       [5, 6]]), array([[3, 4],
       [7, 8]])]


 ## Section 9: Delete, Insert, Append, Concatenate

##### Q23. Delete the second row from the following array a = np.array([[1, 2], [3, 4], [5, 6]])

In [71]:
a = np.array([[1, 2], [3, 4], [5, 6]])
print(np.delete(a , 1 , axis = 0))

[[1 2]
 [5 6]]


#####  Q24. Insert a row [9, 9] at index 1 in the above array.

In [75]:
a = np.array([[1, 2], [3, 4], [5, 6]])
print(np.insert(a, 1 ,  [9,9] , axis = 0))

[[1 2]
 [9 9]
 [3 4]
 [5 6]]


##### Q25. Append [7, 8] as a new row to:a = np.array([[1, 2], [3, 4]])

In [84]:
a = np.array([[1, 2], [3, 4]])
b = np.array([[7,8]])
result = np.append(a, b , axis = 0)
print(result)

[[1 2]
 [3 4]
 [7 8]]


##### Q26. Concatenate two arrays [1, 2, 3] and [4, 5, 6] into one.

In [87]:
a = np.array([1, 2, 3])
b = np.array([4,5,6])
result = np.concatenate((a , b ))
print(result)

[1 2 3 4 5 6]


## Section 10: Broadcasting & Vectorization

##### Q27. Add the array [1, 2, 3] to each row of the 2D array: b = np.array([[10], [20], [30]])

In [88]:
a = np.array([1, 2, 3])
b = np.array([[10], [20], [30]])
print(a +  b)

[[11 12 13]
 [21 22 23]
 [31 32 33]]


##### Q28. Multiply each element of [1, 2, 3, 4, 5] by 2 without using a loop.


In [89]:
a = np.array([1, 2, 3 , 4,5])
print(a*2)

[ 2  4  6  8 10]


## Section 11: Handling Missing Values

##### Q29. Check for NaNs in: np.array([1, np.nan, 2])

In [91]:
a = np.array([1, np.nan, 2])
print(np.isnan(a))

[False  True False]


##### Q30. Replace NaNs and infinite values in: np.array([np.nan, np.inf, -np.inf])

In [97]:
a = np.array([np.nan, np.inf, -np.inf])
replace = np.nan_to_num(a , nan = 0 , posinf = 1000 , neginf = 2000)
print(replace)

[   0. 1000. 2000.]
