In [12]:
import numpy as np

 # Create a 1D NumPy array of numbers from 0 to 9.
arr = np.arange(0 , 10)
print(arr)




[0 1 2 3 4 5 6 7 8 9]


In [14]:
# Create a 3x3 array of all True values.
arr = np.full([3,3] , True)
print(arr)

[[ True  True  True]
 [ True  True  True]
 [ True  True  True]]


In [18]:
# Create an array of 10 random integers between 1 and 100.
arr = np.random.randint(1 , 101,size = 10)
print(arr)

[60 92 10 50 18  8  8 56 31 83]


In [25]:
# Print the dimension ,  shape, size, and data type of a 2D array.
arr_2d = np.array([[1,2,3],
                  [4,5,6],
                  [7,8,9]])
print("Dimension : " , arr_2d.ndim)
print("Shape  : " , arr_2d.shape)
print("Size  : " , arr_2d.size)
print("Data type  : " , arr_2d.dtype)

Dimension :  2
Shape  :  (3, 3)
Size  :  9
Data type  :  int32


In [30]:
# Create a 4x4 array of zeros and change the data type to int32.
arr = np.zeros([4,4])
print(arr ) 
print("Data type  : " , arr.dtype)
print("Change Data type  : " , arr.astype(int))

[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]
Data type  :  float64
Change Data type  :  [[0 0 0 0]
 [0 0 0 0]
 [0 0 0 0]
 [0 0 0 0]]


In [36]:
 # Create a 1D array of 12 elements and reshape it into a 3x4 matrix
arr = np.arange(1,13)
print(arr)
reshape = arr.reshape(3,4)
print(reshape)

[ 1  2  3  4  5  6  7  8  9 10 11 12]
[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


In [48]:
# Extract the second row and third column from a 3x3 array.
arr = np.arange(9).reshape([3,3])
print(arr)
print("\n")

row = arr[1 ,:]
print(row)
col = arr[: , 2]
print(col)

[[0 1 2]
 [3 4 5]
 [6 7 8]]


[3 4 5]
[2 5 8]


In [68]:
# Create a 5x5 matrix and set the inner 3x3 to ones, while keeping border as zeros.
arr = np.zeros((5,5),dtype= int)
print(arr)
print("\n")
arr[1:4 , 1:4] = 1 # Row start : row end , col start : col end
print(arr)

[[0 0 0 0 0]
 [0 0 0 0 0]
 [0 0 0 0 0]
 [0 0 0 0 0]
 [0 0 0 0 0]]


[[0 0 0 0 0]
 [0 1 1 1 0]
 [0 1 1 1 0]
 [0 1 1 1 0]
 [0 0 0 0 0]]


In [75]:
# Perform element-wise addition, subtraction, multiplication, and division
# between two arrays of the same shape.
arr1 = np.array([[1,2,3],
                  [4,5,6]])
arr2 = np.array([[7,8,9],
                 [4,5,6]])
print( "add : " , arr1 + arr2 )
print( "sun : " , arr1 - arr2 )
print( "mult : " , arr1 * arr2 )
print( "div : " , arr1 / arr2 )


add :  [[ 8 10 12]
 [ 8 10 12]]
sun :  [[-6 -6 -6]
 [ 0  0  0]]
mult :  [[ 7 16 27]
 [16 25 36]]
div :  [[0.14285714 0.25       0.33333333]
 [1.         1.         1.        ]]


In [76]:
#Normalize a 1D array(subtract mean and divide by standard deviation).normalized_arr=(arr - mean)/std

arr = np.array([10, 20, 30, 40, 50])
mean = np.mean(arr)
std = np.std(arr)
normalized_arr=(arr - mean)/std
print(normalized_arr)

[-1.41421356 -0.70710678  0.          0.70710678  1.41421356]


In [84]:
# Find the mean, median, and standard deviation of a given array.
arr = np.array([10, 20, 30, 40, 50])
mean = np.mean(arr)
median =np.median(arr)
std = np.std(arr)
print(f"mean : {mean}")
print(f"median : {median}")
print(f"standard deviation : {std}")

mean : 30.0
median : 30.0
standard deviation : 14.142135623730951


In [87]:
# Find the indices of the maximum and minimum elements in an array.
arr = np.array([10, 20, 30, 40, 50])
max = np.argmax(arr)
print(f"index of maximum element : {max}")

min = np.argmin(arr)
print(f"index of minimum element : {min}")

index of maximum element : 4
index of minimum element : 0


In [97]:
# Create a random array of 15 integers and filter out all values less than 10.
arr = np.random.randint ( 1 , 20 , size = 15)
print(arr)
filter = arr[arr < 10]
print(arr < 10)

[10 17 10  4  1  8 19  3 18 15  9  9 15 10  2]
[False False False  True  True  True False  True False False  True  True
 False False  True]


In [101]:
# Replace all values greater than 50 with 50 in a given array

arr = np.random.randint ( 1 , 80 , size = 10)
print(arr)
arr[arr > 50 ] = 50
print(arr)

[58 22 71 42 10 17 65 15 30 19]
[50 22 50 42 10 17 50 15 30 19]


In [102]:
#  Broadcasting =>Add a 1D array [1,2,3] to each row of a 3x3 matrix.
arr1 =np.array([1,2,3])
arr2 = np.array([[1,2,3],
                  [4,5,6],
                  [7,8,9]])
print(arr1 + arr2)



[[ 2  4  6]
 [ 5  7  9]
 [ 8 10 12]]


In [103]:
# Multiply two matrices using dot product
A = np.array([[1, 2],
              [3, 4]])

B = np.array([[5, 6],
              [7, 8]])
# multiply using fot product
result = np.dot(A , B)
print(result)

[[19 22]
 [43 50]]


In [110]:
# Given a 4x4 matrix, extract all even-numbered rows and odd-numbered columns.
arr = np.random.randint( 1, 10 , size = [4,4])
print(arr)
even_rows =arr[1::2]
print(f"Even rows : {even_rows}")

odd_col =arr[0::2]
print(f"odd columns : {odd_col}")

[[8 1 5 3]
 [3 3 5 6]
 [1 6 9 1]
 [9 4 9 1]]
Even rows : [[3 3 5 6]
 [9 4 9 1]]
odd columns : [[8 1 5 3]
 [1 6 9 1]]


In [117]:
# Find the union, intersection, and set difference between two 1D arrays
arr1 = np.random.randint(1 , 10 , size = 6)
arr1 = np.random.randint(1 , 10 , size = 6)

union = np.union1d(arr1 , arr2)
intersection = np.intersect1d(arr1 , arr2)
set_difference = np.setdiff1d(arr1 , arr2)
print(f"union : {union}")
print(f"intersection : {intersection}")
print(f"set_difference : {set_difference}")

union : [0 1 2 3 4 7 8]
intersection : [2 3]
set_difference : [7 8]


In [125]:
# Write a NumPy function that takes a 2D array and returns the row with the highest_sum

arr_2d = np.array([[1,2,3],
                  [4,5,6],
                  [7,8,9]])
Row_sum = np.sum(arr_2d , axis =1)
print(Row_sum)
max_index = np.argmax(Row_sum)
print(arr_2d[max_index])

[ 6 15 24]
[7 8 9]


In [139]:
""" Generate a 10x10 array with random values and find the 
position (row, column) of the maximum element. """


# Step 1
arr = np.random.randint(1, 10, size=[10, 10])
print("Array:\n", arr)

# Step 2
max_index = np.argmax(arr)
print("Flattened index of max element:", max_index)

# Step 4
max_position = np.unravel_index(max_index , arr.shape)
print("Position of max element (row, column):", max_position)

# Step 5
print("Maximum element value:", arr[max_position])


Array:
 [[4 6 3 1 4 6 5 7 1 5]
 [5 3 5 7 4 5 7 5 8 9]
 [7 2 5 4 2 1 1 2 6 8]
 [9 4 1 7 6 9 2 4 6 8]
 [1 1 3 7 6 9 3 6 3 8]
 [7 7 3 5 6 4 7 8 3 2]
 [1 2 6 6 4 3 4 3 5 2]
 [7 1 6 5 9 4 9 6 1 4]
 [1 4 1 7 7 7 3 3 2 3]
 [2 2 2 1 2 1 4 5 9 2]]
Flattened index of max element: 19
Position of max element (row, column): (1, 9)
Maximum element value: 9
