In [1]:
!pip install numpy

In [2]:
import numpy as np

In [5]:
python_list = [1,2,3,4,5]
print(python_list)

import numpy as np

numpy_array = np.array([1,2,3,4,5])
print(numpy_array)

#  numpu array ma comma nahi aya mtlb memory efficiently use ki  gai ha


[1, 2, 3, 4, 5]
[1 2 3 4 5]


In [6]:
arr_2d = np.array([[1,2,3],
                  [4,5,6],
                  [7,8,9]])
print(arr_2d)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [8]:
arr_3d = np.array([[[1,2,3], # first layer (2 rows and 3 column)
                  [4,5,6]],
                  [[7,8,9], # second layer (2 rows and 3 column)
                  [1,2,3]]])

print(arr_3d)

[[[1 2 3]
  [4 5 6]]

 [[7 8 9]
  [1 2 3]]]


In [9]:
# convert list into a array
arr = np.array([1, 2,3])
print(arr)

[1 2 3]


In [10]:
# default values  np.zeros(shape) shape mtlb size
arr = np.zeros(3)
print(arr)

[0. 0. 0.]


In [12]:
arr = np.ones([2,3]) # 2 by 3  matrix
print(arr)

[[1. 1. 1.]
 [1. 1. 1.]]


In [14]:
# full (shape , value)  jb zero or one nahi dani apni mrzi sy koi number dana ho tu
arr = np.full([2,2] , 7)
print(arr)

[[7 7]
 [7 7]]


In [15]:
# creating sequence  of number in numpy => arange(start , stop, step) return array
arr = np.arange(1, 10 , 2)
print(arr)

[1 3 5 7 9]


In [19]:
# creating identity matrices 
arr = np.eye(4)
print(arr)

[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]


In [3]:
# shape => return integer number

import numpy as np

arr_2d = np.array([[1,2,3],
                   [4,5,6]])
print(arr_2d.shape) # 2 show => 2 row and 3 show => 3 column

(2, 3)


In [4]:
# size => return total number of element in array
arr_2d = np.array([[1,2,3],
                   [4,5,6]])
print(arr_2d.size)

6


In [10]:
# ndim => no of dimension
arr_1d = np.array([1,2,3])

arr_2d = np.array([[1,2,3],
                   [4,5,6]])

arr_3d = np.array([[[1,2,3],
                   [4,5,6]],
                   [[7,8,9],
                   [1,2,3]]])

print(arr_1d.ndim)
print(arr_2d.ndim)
print(arr_3d.ndim)


1
2
3


In [19]:
# dtype => check data type
arr1 = np.array([1,2,3, 4.5])
arr2 = np.array([1,2,3, 4])
arr3 = np.array([1,2,3, "aqsa"])



print(arr1.dtype)
print(arr2.dtype)
print(arr3.dtype)

float64
int32
<U11


In [22]:
# astype => chnage data type of array

arr = np.array([1.3,2.0,3.8, 4.5])
print(arr)
print(arr.dtype)

int_arr = arr.astype(int)

print(int_arr)
print(int_arr.dtype)

[1.3 2.  3.8 4.5]
float64
[1 2 3 4]
int32


In [25]:
# Mathametical operation => original array chnage nahi hota
arr = np.array([10 ,20 ,30, 40])
print(arr + 5 )
print(arr)
       

[15 25 35 45]
[10 20 30 40]


In [26]:
arr = np.array([10 ,20 ,30, 40])
print(arr - 5 )
print(arr * 2)
print(arr ** 2)

[ 5 15 25 35]
[20 40 60 80]
[ 100  400  900 1600]


In [30]:
# aggregate function
arr = np.array([10 ,20 ,30, 40])
print(np.sum(arr))
print(np.mean(arr))
print(np.min(arr))
print(np.max(arr))
print(np.std(arr))
print(np.var(arr))

100
25.0
10
40
11.180339887498949
125.0


In [33]:
# indexing 

# access 
# array [index]   for 1d array
# array [row , column ] for 2d and others

arr = np.array([10 ,20 ,30, 40])
print(arr[0], arr[2] , arr[-1])


10 30 40


In [34]:
arr = np.array([10 ,20 ,30, 40])
print(arr[10])

IndexError: index 10 is out of bounds for axis 0 with size 4

In [35]:
arr_2d = np.array([[1,2,3],
                   [4,5,6]])
print(arr_2d[1,0]) #accessing element row 1 , column 2

arr_3d = np.array([[[1,2,3],
                   [4,5,6]], # depth 0
                   
                   [[7,8,9], # depth 1
                   [1,2,3]]])

print(arr_3d[1][0][1]) #accessing element depth 1 row 0 , column 1

4
8


In [40]:
# slicing => array[start , stop , step] stop => excluded , step => default value 1

# arr[start : end] , start to end -1 , negative step -1 reverse

arr = np.array([10 ,20 ,30, 40,50,60,70,80])
print(arr[1:5]) # 1 to 4
print(arr[:5]) # start from 0
print(arr[::2]) # start or end sy pora ho ga  and pick every second element
print(arr[::-1]) # reverse

[20 30 40 50]
[10 20 30 40 50]
[10 30 50 70]
[80 70 60 50 40 30 20 10]


In [42]:
# fancy indexing => selecting multiple elements at once 
#(usually helps when you have to select no sequence element)
# fancy element ma array as a list pass krna ha (always create copy) 
arr = np.array([10 ,20 ,30, 40,50,60,70,80])
print(arr[[0,2,4]]) # 0 ,2 , 4 wala element chaya

[10 30 50]


In [44]:
# boolean masking =>  filtering data  based on condition agr condition fullfill ho ri  ha tu return ho ga wrna nahi
arr = np.array([10 ,20 ,30, 40,50,60,70,80])
print(arr[arr > 55 ])
print(arr[arr > 100 ])


[60 70 80]
[]


In [47]:
# reshapinng and manipulation => reshape(row, columns)
arr = np.array([10 ,20 ,30, 40,50,60])
reshape = arr.reshape(2,3)
print(reshape)

[[10 20 30]
 [40 50 60]]


In [48]:
reshape = arr.reshape(3,3)
print(reshape)

ValueError: cannot reshape array of size 6 into shape (3,3)

In [49]:
arr = np.array([10 ,20 ,30, 40,50,60,70,80])
reshape = arr.reshape(2,2,2) # 2 blocks hr block ma 2 row and 2 column
print(reshape)

[[[10 20]
  [30 40]]

 [[50 60]
  [70 80]]]


In [52]:
# flattening array => convert multi dimensional array into 1D array
# raval => returns a view (original array ma modification ho ge)
# flatten => returns a copy (original array ma modification  nahi ho ge)
arr_2d = np.array([[1,2,3],
                   [4,5,6]])
print(arr_2d.ravel())

arr_3d = np.array([[[1,2,3],
                   [4,5,6]], # depth 0
                   
                   [[7,8,9], # depth 1
                   [1,2,3]]])
print(arr_3d.flatten())
print(arr_2d)
print(arr_3d)





[1 2 3 4 5 6]
[1 2 3 4 5 6 7 8 9 1 2 3]
[[1 2 3]
 [4 5 6]]
[[[1 2 3]
  [4 5 6]]

 [[7 8 9]
  [1 2 3]]]


In [3]:
# advanced numpy
# add

import numpy as np

arr = np.array([10 ,20 ,30, 40,50,60,70,80])
new_arr = np.insert(arr , 2, 20 )
print(new_arr)
print(arr) # original change nahi hota

[10 20 20 30 40 50 60 70 80]
[10 20 30 40 50 60 70 80]


In [5]:
arr_2d = np.array([[1,2,3],
                   [4,5,6]])
# insert a new row at index 1
new_arr_2d = np.insert(arr_2d , 1, [5,6,7] , axis=0)
print(new_arr_2d)

[[1 2 3]
 [5 6 7]
 [4 5 6]]


In [7]:
arr_2d = np.array([[1,2,3],
                   [4,5,6]])
# insert a new column at index 1
new_arr_2d = np.insert(arr_2d , 1, [5,6] , axis=1)
print(new_arr_2d)

[[1 5 2 3]
 [4 6 5 6]]


In [9]:
arr_2d = np.array([[1,2,3],
                   [4,5,6]])
# axis none isy flatten kr dy ga
new_arr_2d = np.insert(arr_2d , 1, [5,6] , axis=None)
print(new_arr_2d)

[1 5 6 2 3 4 5 6]


In [10]:
# append => add element at the end , original array unchanged rhy ga

arr = np.array([10 ,20 ,30, 40,50])
new = np.append(arr ,[60,70,80])
print(new)

[10 20 30 40 50 60 70 80]


In [11]:
# concatente

arr1 = np.array([10 ,20 ,30, 40])
arr2 = np.array([50 ,60 ,70, 80])
new = np.concatenate((arr1 , arr2))
print(new)

[10 20 30 40 50 60 70 80]


In [14]:
arr1 = np.array([[1,2,3],
                   [4,5,6]])
arr2 = np.array([[1,2,3],
                   [4,5,6]])
# axis = 0 ,  vertically stacking
new = np.concatenate((arr1 , arr2,) ,axis = 0)
print(new)

[[1 2 3]
 [4 5 6]
 [1 2 3]
 [4 5 6]]


In [15]:
arr1 = np.array([[1,2,3],
                   [4,5,6]])
arr2 = np.array([[1,2,3],
                   [4,5,6]])
# axis = 1 , horizontally stacking
new = np.concatenate((arr1 , arr2,) ,axis = 1)
print(new)

[[1 2 3 1 2 3]
 [4 5 6 4 5 6]]


In [17]:
#delete => removing elements at specific position
arr1 = np.array([10 ,20 ,30, 40])
new = np.delete(arr1 , 0)
print(new)
print(arr1) # unchanged original

[20 30 40]
[10 20 30 40]


In [21]:
arr = np.array([[1,2,3],
                   [4,5,6]])
new = np.delete(arr , 0 , axis=0)
print(new)

[[4 5 6]]


In [22]:
arr = np.array([[1,2,3],
                   [4,5,6]])
new = np.delete(arr , 0 , axis=1)
print(new)

[[2 3]
 [5 6]]


In [23]:
# stacking => combine multiple array , Vstack => row , hstack => column
arr1 = np.array([10 ,20 ,30, 40])
arr2 = np.array([50 ,60 ,70, 80])
new = np.vstack((arr1 , arr2)) # vertically
print(new)

[[10 20 30 40]
 [50 60 70 80]]


In [24]:
arr1 = np.array([10 ,20 ,30, 40])
arr2 = np.array([50 ,60 ,70, 80])
new = np.hstack((arr1 , arr2)) # horizontally
print(new)

[10 20 30 40 50 60 70 80]


In [26]:
# splitting => divide into subarray  
# np.split()
arr = np.array([10 ,20 ,30, 40, 50 ,60 ,70, 80])
new = np.split(arr , 2) # 2 parts am divide krp
print(new)
print(arr) # unchnaged originall

new = np.split(arr , 4) # 4 parts am divide krp
print(new)

[array([10, 20, 30, 40]), array([50, 60, 70, 80])]
[10 20 30 40 50 60 70 80]
[array([10, 20]), array([30, 40]), array([50, 60]), array([70, 80])]


In [27]:
arr = np.array([10 ,20 ,30, 40, 50 ,60 ,70, 80])
new = np.split(arr , 10) # array li length sy ziyada parts ma divide kia ti value error ay ga
print(new)

ValueError: array split does not result in an equal division

In [28]:
# np.hsplit()
arr = np.array([10 ,20 ,30, 40, 50 ,60 ,70, 80])
new = np.hsplit(arr , 2) # 2 parts am divide krp
print(new)

[array([10, 20, 30, 40]), array([50, 60, 70, 80])]


In [35]:
# np.vsplit()
arr = np.array([[1,2,3,0],
                   [4,5,6,0],
                   [1,2,3,0],
                   [4,5,6,0]])
new = np.vsplit(arr , 2) # 2 parts am divide krp
print(new)

[array([[1, 2, 3, 0],
       [4, 5, 6, 0]]), array([[1, 2, 3, 0],
       [4, 5, 6, 0]])]


In [43]:
# brodcasting
prices = [100,200,300]
discount = 10
final = []
for price in prices:
    discounted = price - (price * discount/100)
    final.append(discounted)

print(final)


[90.0, 180.0, 270.0]
270.0


In [47]:
# solution
prices = np.array([100,200,300 , 400])
discount = 10
finall =  prices - (prices * discount/100)
print(finall)

[ 90. 180. 270. 360.]


In [48]:
# single value
arr = np.array([100,200,300 , 400])
result = arr * 2
print(result)

[200 400 600 800]


In [50]:
# 1d to 2d
# expanding element
arr = np.array([[1,2,3],
                   [4,5,6]])
vector = np.array([10,20,30])
result =  arr + vector
print(result)
                

[[11 22 33]
 [14 25 36]]


In [51]:
# incompatible shape => eror
arr1 = np.array([[1,2,3],
                   [4,5,6]])
arr2 = np.array([1,2])
result = arr1 + arr2
print(result)

ValueError: operands could not be broadcast together with shapes (2,3) (2,) 

In [6]:
import numpy as np
arr1 = np.array([[1,2,3],
                   [4,5,6]])

arr2 = np.array([1,2]).reshape(2,1)
print(arr2)

result = arr1 + arr2
print(result)

[[1]
 [2]]
[[2 3 4]
 [6 7 8]]


In [8]:
# vectorization
l1=[1,2,3]
l2=[4,5,6]
result = [x + y for x,y in zip(l1 , l2) ]
print(result)


[5, 7, 9]


In [9]:
# fast vectorization approach
arr1=np.array([1,2,3])
arr2=np.array([4,5,6])
result = arr1 + arr2
print(result)

[5 7 9]


In [11]:
arr1=np.array([1,2,3])
arr2=np.array([4,5,6])
result = arr1 * arr2
print(result)

arr1=np.array([1,2,3])
print(arr1*3)

[ 4 10 18]
[3 6 9]


In [13]:
# handling missing values
arr = np.array([1,2, np.nan , 4 , np.nan , 6])
print(np.isnan(arr)) # true means is position ma value missing ha

[False False  True False  True False]


In [14]:
# filter out nan values
arr = np.array([1,2, np.nan , 4 , np.nan , 6])
cleaned = arr[~np.isnan(arr)]
print(cleaned)

[1. 2. 4. 6.]


In [ ]:
a

In [15]:
# replace nan values

arr = np.array([1,2, np.nan , 4 , np.nan , 6])
arr[np.isnan(arr)]=0
print(arr)

[1. 2. 0. 4. 0. 6.]


In [18]:
arr = np.array([1,2, np.nan , 4 , np.nan , 6])
replace = np.nan_to_num(arr , nan=100)
print(replace)

[  1.   2. 100.   4. 100.   6.]


In [19]:
# infinite number  => 10*100 1/0
arr = np.array([1,2,np.inf , 4, -np.inf , 6])
print(np.isinf(arr))

[False False  True False  True False]


In [20]:
# replace infinite number to a finite number
arr = np.array([1,2,np.inf , 4, -np.inf , 6])
print(np.isinf(arr))
replace = np.nan_to_num(arr , posinf =1000 , neginf = -1000) # posinf => positive infinity
print(replace)

[False False  True False  True False]
[    1.     2.  1000.     4. -1000.     6.]
